### ISSUE TITLE
Add DATA_ONLY kwarg for TempalteWorkbook

### ISSUE THREAD

**Issue by stascrash** [SverkerSbrg/openpyxl-templates#1]
Some Excel files have Formulas in Cell-Values. I cannot read the calculated value, as the constructor for TemplateWorkbook does not support this "data_only" argument.
It would be nice to have this exposed and forwarded to "load_workbook" method.
here is link to the parameter i refer to:
http://openpyxl.readthedocs.io/en/default/usage.html?highlight=data_only

**Comment by SverkerSbrg** [comment]
Great, thank you!

**Comment by stascrash** [comment]
Hey, I just got your module here today, and Thank you for getting this up in opensource!
it has saved me a lot of time just in one day.

Sent from Mail for Windows 10
