### ISSUE TITLE
Support xlsm file type

### ISSUE THREAD

**Issue by cpa-level-it** [SverkerSbrg/openpyxl-templates#6]
In its current state openpyxl-templates doesn't support xlsm files.
It's able to correctly open a xlsm file, replace its content but when saving all the VBA macro are lost.
If the file has still the xlsm extension, then Excel will fail to open it.
When the file is renamed to .xslx, Excel can open it but the macro are missing.

A solution is to use the `keep_vba=True` parameters in the load_workbook method.
Then when saving the file all VBA macros will be added back and it will correctly open in Excel.

**Comment by SverkerSbrg** [comment]
I've added the keep_vba argument to the TemplatedWorkbook constuctor and passed it to the underlying workbook. Could you verify that it is working properly before I push to pypi? Prefferably as tests.

**Comment by rajasd08** [comment]
Hi @SverkerSbrg , Is this fix working as expected, have you found any issues so far ? Thanks !
