### ISSUE TITLE
Issue with column order

### ISSUE THREAD

**Issue by stampedeboss** [SverkerSbrg/openpyxl-templates#7]
Running Python 2.7 and none of the examples work due to the order of the columns not being created in the sequence defined.

Looking at the code it appears the columns are loaded in the __new__ method from the class dictionary and dictionaries do not maintain order.

**Comment by SverkerSbrg** [comment]
Hi, 

The package is written for python 3, pyhon 2 adaptions are unfortunately untested. 

The class dict is supposed to be repaced with an OrderedDict by the OrderedType metaclass (found [here](https://github.com/SverkerSbrg/openpyxl-templates/blob/master/openpyxl_templates/utils.py). I'll try to do some digging but feel free to look into how this is done on python 2

**Comment by stampedeboss** [comment]
I have modified the routines and have it working. If interested I can provide the required changes. 

Added 3 lines to TableColumn and modified the OrderedType new routine to address the issue. Very simple changes.

**Comment by stampedeboss** [comment]
The issue centers around the dict in python 2 does not support order whereas python 3.4 and above does. I basically on initializing a table column I initialized the column_index the leveraged it in the ordered object. 

Seems that it is initialized much later in the process which I didn’t impact.
